//*****************************************************************************
// Copyright (c) 2014 Texas Instruments Incorporated.  All rights reserved.
// Software License Agreement
// 
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions
//   are met:
// 
//   Redistributions of source code must retain the above copyright
//   notice, this list of conditions and the following disclaimer.
// 
//   Redistributions in binary form must reproduce the above copyright
//   notice, this list of conditions and the following disclaimer in the
//   documentation and/or other materials provided with the  
//   distribution.
// 
//   Neither the name of Texas Instruments Incorporated nor the names of
//   its contributors may be used to endorse or promote products derived
//   from this software without specific prior written permission.
// 
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
// OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// This file was automatically generated by the Tiva C Series PinMux Utility
// Version: 1.0.4
//
//*****************************************************************************

#include <stdint.h>
#include <stdbool.h>
#include "toggle6.h"
#include "../../../../inc/hw_types.h"
#include "../../../../inc/hw_memmap.h"
#include "../../../../inc/hw_gpio.h"
#include "../../../../driverlib/sysctl.h"
#include "../../../../driverlib/pin_map.h"
#include "../../../../driverlib/rom_map.h"
#include "../../../../driverlib/gpio.h"
#include "inc/tm4c123gh6pm.h"	// Manually added by the programmer


//*****************************************************************************

#define 	RED_MASK 		0x02	// PF1, 2^1 = 2 
#define   GREEN_MASK  0x08	// PF3, 2^3 = 8

#define		SW2					0x01 // PF0, 2^0 = 1
#define 	SW1					0x10 // PF4, 2^4 = 16

void
PortFunctionInit(void)
{
    //
    // Enable Peripheral Clocks 
    //
    MAP_SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOF);
	
    //
    // Enable pin PF0 for GPIOInput
    //

    //
    //First open the lock and select the bits we want to modify in the GPIO commit register.
    //
    HWREG(GPIO_PORTF_BASE + GPIO_O_LOCK) = GPIO_LOCK_KEY;
    HWREG(GPIO_PORTF_BASE + GPIO_O_CR) = 0x1;

    //
    //Now modify the configuration of the pins that we unlocked.
    //
    MAP_GPIOPinTypeGPIOInput(GPIO_PORTF_BASE, GPIO_PIN_0);

    //
    // Enable pin PF4 for GPIOInput
    //
    MAP_GPIOPinTypeGPIOInput(GPIO_PORTF_BASE, GPIO_PIN_4);

    //
    // Enable pin PF1 for GPIOOutput
    //
    MAP_GPIOPinTypeGPIOOutput(GPIO_PORTF_BASE, GPIO_PIN_1);

    //
    // Enable pin PF3 for GPIOOutput
    //
    MAP_GPIOPinTypeGPIOOutput(GPIO_PORTF_BASE, GPIO_PIN_3);
		
		//
		// **Code below added manually by programmer.**
		// **#include "inc/tm4c123gh6pm.h" is needed for this code.**
		// Enable pull-up on PF0
		// 
		GPIO_PORTF_PUR_R |= SW2;
		
		// Enable pull-up on PF4
		// 
		GPIO_PORTF_PUR_R |= SW1;
		
}

int main(void)
{
    uint8_t toggle;

		int clockDelay = ((SysCtlClockGet() /2 )/3);
		
	
		//initialize the GPIO ports	
		PortFunctionInit();
	
    //
    // Loop forever.
    //
    while(1)
    {

			// When SW2 is pressed, all LED are off. 
			if(GPIOPinRead(GPIO_PORTF_BASE, GPIO_PIN_0)==0x00)
			{
				GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_1, 0x00);
				GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_3, 0x00);
			}
			
			// When SW1 is pressed, red and blue LEDs are OFF, and green LED toggles half second.
			else if((GPIOPinRead(GPIO_PORTF_BASE, GPIO_PIN_4)==0x00) && (GPIOPinRead(GPIO_PORTF_BASE, GPIO_PIN_1)==0x00))
			{
				GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_1, 0x00);
				SysCtlDelay(clockDelay);
				toggle ^= GREEN_MASK;
				GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_3, toggle);
				
			} 
			else // SW1 is NOT pressed, red LED toggles for half second, blue and green LEDs are OFF.
			{
				GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_3, 0x00);
				SysCtlDelay(clockDelay);
				toggle ^= RED_MASK;
				GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_1, toggle);
				
			}

    }
}
